# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statsHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=255)),
                ('gearNumber', models.IntegerField()),
                ('twoPointer', models.IntegerField()),
            ],
        ),
    ]
