# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsHolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=25)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('fixture_id', models.AutoField(primary_key=True, serialize=False)),
                ('fixture_date', models.DateField()),
                ('venue', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=25)),
                ('player_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Substitutions',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sub_in', models.BooleanField()),
                ('sub_out', models.BooleanField()),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.Fixture')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=25)),
                ('league', models.CharField(max_length=25)),
                ('home_location', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.User'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_set', to='statsHolder.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_set', to='statsHolder.Team'),
        ),
        migrations.AddField(
            model_name='action',
            name='fixture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.Fixture'),
        ),
        migrations.AddField(
            model_name='action',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsHolder.Player'),
        ),
    ]
